version: '3'
services:
  graphql:
    image: "node:alpine"
    working_dir: "/service"
    volumes:
      - ./graphql/:/service
    command: ['node_modules/.bin/nodemon', '-w', 'lib/**/*', 'lib/index.js']
    ports:
      - "4000:80"
  ux:
    image: "nginx:alpine"
    volumes:
      - ./etc/ux-nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ux/build:/usr/share/nginx/html:ro
    ports:
      - "3000:80"
  # Basic Prisma Setup
  # https://www.prisma.io/docs/get-started/01-setting-up-prisma-new-database-TYPESCRIPT-t002/#set-up-and-connect-prisma-with-a-database
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: ~
